version: "3"
services:
  node:
    container_name: blog_node
    build:
      context: "./docker/node"
      dockerfile: "Dockerfile"
    image: node:18.12-alpine
    ports:
      - 3000:3000
      - 3002:3002
      - 6006:6006
    tty: true
    # mongoも入れるので共有を./直下にする
    volumes:
      - .:/app
    networks:
      - blog_node
    depends_on:
      - mongo
networks:
  blog_node:
    driver: "bridge"
