// helpers.ts
export const categories = [
  { id: '1', name: 'Technology' },
  { id: '2', name: 'Lifestyle' },
  { id: '3', name: 'Travel' },
];

export const tags = [
  { id: '1', name: 'JavaScript' },
  { id: '2', name: 'React' },
  { id: '3', name: 'Web Development' },
  { id: '4', name: 'Python' },
  { id: '5', name: 'TypeScript' },
  { id: '6', name: 'Node.js' },
  { id: '7', name: 'Docker' },
  { id: '8', name: 'AWS' },
  { id: '9', name: 'DevOps' },
  { id: '10', name: 'Machine Learning' },
  { id: '11', name: 'Health' },
  { id: '12', name: 'Fitness' },
  { id: '13', name: 'Nutrition' },
  { id: '14', name: 'Mindfulness' },
  { id: '15', name: 'Productivity' },
  { id: '16', name: 'Work-Life Balance' },
  { id: '17', name: 'Home Decor' },
  { id: '18', name: 'Cooking' },
  { id: '19', name: 'Fashion' },
  { id: '20', name: 'Adventure' },
  { id: '21', name: 'Backpacking' },
  { id: '22', name: 'City Guides' },
  { id: '23', name: 'Food Tourism' },
  { id: '24', name: 'Photography' },
  { id: '25', name: 'Budget Travel' },
  { id: '26', name: 'Luxury Travel' },
  { id: '27', name: 'Digital Nomad' },
  { id: '28', name: 'Sustainable Travel' },
  { id: '29', name: 'Cultural Experience' },
  { id: '30', name: 'Travel Tips' },
];
